-- Bundled Lua Script
-- Generated by Lua Bundler
-- https://github.com/alfin-efendy/lua-bundler

local EmbeddedModules = {}

-- Module: module/collectfruit.lua
EmbeddedModules["module/collectfruit.lua"] = function()
    -- collectfruit.lua (Alok_Hub)
    -- Auto Collect Fruit using GameEvents.Crops.Collect RemoteEvent
    -- Based on Alok_Hub/grow-a-garden/farm/plant.lua

    local Players = game:GetService("Players")
    local ReplicatedStorage = game:GetService("ReplicatedStorage")

    local LP = Players.LocalPlayer
    local username = LP.Name

    local M = {}

    ----------------------------------------------------------------
    -- ENV / GLOBALS
    ----------------------------------------------------------------
    local G = (getgenv and getgenv()) or _G

    ----------------------------------------------------------------
    -- CONFIG
    ----------------------------------------------------------------
    local LOOP_TICK_SEC = 2
    local COLLECT_DELAY = 0.1
    local MAX_HOLDABLE = 200

    -- Toggle global
    G.AUTO_COLLECT_FRUIT_ENABLED = (G.AUTO_COLLECT_FRUIT_ENABLED == true)

    ----------------------------------------------------------------
    -- INTERNAL STATE
    ----------------------------------------------------------------
    local running = false

    ----------------------------------------------------------------
    -- GET CROP COLLECT REMOTE
    ----------------------------------------------------------------
    local CropsCollect = nil
    pcall(function()
        CropsCollect = ReplicatedStorage:WaitForChild("GameEvents", 5):WaitForChild("Crops", 5):WaitForChild("Collect", 5)
    end)

    -- CropsCollect loaded silently

    ----------------------------------------------------------------
    -- FIND OWN FARM
    ----------------------------------------------------------------
    local function getOwnFarm()
        local farmsFolder = workspace:FindFirstChild("Farm")
        if not farmsFolder then return nil end

        for _, farm in ipairs(farmsFolder:GetChildren()) do
            local ok, ownerValue = pcall(function()
                return farm:FindFirstChild("Important")
                    and farm.Important:FindFirstChild("Data")
                    and farm.Important.Data:FindFirstChild("Owner")
                    and farm.Important.Data.Owner.Value
            end)

            if ok and ownerValue == username then
                return farm
            end
        end

        return nil
    end

    ----------------------------------------------------------------
    -- CHECK IF FRUIT IS ELIGIBLE TO HARVEST
    ----------------------------------------------------------------
    local function isEligibleToHarvest(fruit)
        if not fruit or not fruit:IsA("Model") then return false end

        local prompt = fruit:FindFirstChild("ProximityPrompt", true)
        if not prompt then
            local customPrompt = string.format("%s_ProximityPrompt", fruit.Name)
            prompt = fruit:FindFirstChild(customPrompt, true)
        end

        if not prompt then return false end
        if not prompt.Enabled then return false end

        return true
    end

    ----------------------------------------------------------------
    -- COLLECT SINGLE FRUIT
    ----------------------------------------------------------------
    local function collectFruit(fruit)
        if not CropsCollect then return false end
        if not fruit then return false end

        local success, err = pcall(function()
            CropsCollect:FireServer({fruit})
        end)

        return success
    end

    ----------------------------------------------------------------
    -- COLLECT ALL FRUITS FROM OWN FARM
    ----------------------------------------------------------------
    local function collectAllFruits()
        local farm = getOwnFarm()
        if not farm then return 0 end

        local important = farm:FindFirstChild("Important")
        if not important then return 0 end

        local plants = important:FindFirstChild("Plants_Physical")
        if not plants then return 0 end

        local count = 0

        for _, plant in ipairs(plants:GetChildren()) do
            if not G.AUTO_COLLECT_FRUIT_ENABLED then break end

            local fruitsFolder = plant:FindFirstChild("Fruits")
            if fruitsFolder then
                for _, fruit in ipairs(fruitsFolder:GetChildren()) do
                    if not G.AUTO_COLLECT_FRUIT_ENABLED then break end

                    if isEligibleToHarvest(fruit) then
                        if collectFruit(fruit) then
                            count = count + 1
                            task.wait(COLLECT_DELAY)
                        end
                    end
                end
            end
        end

        return count
    end

    ----------------------------------------------------------------
    -- LOOP
    ----------------------------------------------------------------
    local function collectLoop()
        while running do
            if G.AUTO_COLLECT_FRUIT_ENABLED == true then
                collectAllFruits()
            end
            task.wait(LOOP_TICK_SEC)
        end
    end

    ----------------------------------------------------------------
    -- PUBLIC API
    ----------------------------------------------------------------
    function M.SetEnabled(on)
        on = (on == true)
        G.AUTO_COLLECT_FRUIT_ENABLED = on

        if on then
            if not running then
                running = true
                task.spawn(collectLoop)
            end
        else
            running = false
        end
    end

    function M.setEnabled(on) return M.SetEnabled(on) end
    function M.start() M.SetEnabled(true) end
    function M.stop() M.SetEnabled(false) end

    function M.IsRunning()
        return running == true and (G.AUTO_COLLECT_FRUIT_ENABLED == true)
    end

    function M.syncFromState()
        local on = (G.AUTO_COLLECT_FRUIT_ENABLED == true)
        M.SetEnabled(on)
    end

    -- Set globals
    _G.AutoCollectFruit = M
    G.AutoCollectFruit = M

    return M

end

-- Module: elephant/elephant.lua
EmbeddedModules["elephant/elephant.lua"] = function()
    -- elephant/elephant.lua
    -- Backend logic untuk auto elephant farming
    local m = {}

    local Core
    local Pet
    local PetTeam
    local HttpService = game:GetService("HttpService")
    local Players = game:GetService("Players")
    local ReplicatedStorage = game:GetService("ReplicatedStorage")

    -- Direct datastore access (like auto_kg) for fresh data
    local ActivePetsService = nil
    pcall(function()
        ActivePetsService = require(ReplicatedStorage.Modules.PetServices.ActivePetsService)
    end)

    -- Storage (username-based path set in Init)
    local SAVE_BASE = "Alok_Hub_KG"
    local SAVE_DIR = SAVE_BASE
    local SAVE_FILE = SAVE_DIR .. "/elephant_config.json"

    -- State
    m.IsRunning = false
    m.SelectedTeamPets = {} -- {guid = true} set of pet GUIDs
    m.TargetWeight = 60.5
    m.MaxPetsInGarden = 3  -- Default 3 (total 8 slots: 5 pet team + 3 target pets)
    m.SelectedPetTypes = {}
    m.MinAgeToEquip = 40  -- Only equip pets with age >= this value
    m.UnequipAtAge = 0     -- Unequip pets when age reaches this value
    m.OnNotify = nil       -- Callback for notifications

    -- Skill Stuck Detection (same as auto_kg)
    m.SkillStuckEnabled = true
    m.SkillStuckThreshold = 15  -- loops without cooldown change = stuck
    m.SkillStuckTolerance = 0.1 -- seconds tolerance
    local SKILL_STUCK = {}  -- [uuid] = { lastCooldown, sameCount }
    -- All skill tokens combined (ELE + XP from auto_kg)
    local ALL_SKILL_TOKENS = {
        "rainbow jumbo blessing", "jumbo blessing", "jumbo",  -- ELE
        "friendly frier", "mining", "rainbow frilled reptile"  -- XP
    }

    ----------------------------------------------------------------
    -- DIRECT DATASTORE ACCESS (like auto_kg for fresh data)
    ----------------------------------------------------------------
    local function getDatastoreBag()
        if not ActivePetsService or not ActivePetsService.GetPlayerDatastorePetData then
            return nil
        end
        local ok, store = pcall(function()
            return ActivePetsService:GetPlayerDatastorePetData(Players.LocalPlayer.Name)
        end)
        if not ok or not store then return nil end
        if not store.PetInventory or not store.PetInventory.Data then return nil end
        return store.PetInventory.Data
    end

    local function getPetAgeFromDatastore(uuid)
        if not uuid or uuid == "" then return nil end

        local bag = getDatastoreBag()
        if not bag then return nil end

        -- Normalize UUID (with and without braces)
        local core = tostring(uuid):match("{?([0-9a-fA-F%-]+)}?") or tostring(uuid)
        local braced = "{" .. core .. "}"

        local rec = bag[core] or bag[braced] or bag[uuid]
        if not rec or type(rec) ~= "table" then return nil end

        local PD = rec.PetData or rec.Data or {}
        return PD.Level or PD.Age or rec.Level or rec.Age or 0
    end

    local function getPetWeightFromDatastore(uuid)
        if not uuid or uuid == "" then return nil end

        local bag = getDatastoreBag()
        if not bag then return nil end

        local core = tostring(uuid):match("{?([0-9a-fA-F%-]+)}?") or tostring(uuid)
        local braced = "{" .. core .. "}"

        local rec = bag[core] or bag[braced] or bag[uuid]
        if not rec or type(rec) ~= "table" then return nil end

        local PD = rec.PetData or rec.Data or {}
        return PD.BaseWeight or rec.BaseWeight or 0
    end

    ----------------------------------------------------------------
    -- INVENTORY SCAN FOR WEBHOOK STATISTICS
    ----------------------------------------------------------------
    -- Weight scale per level (default 0.1 = 10%)
    local WEIGHT_SCALE_PER_LEVEL = 0.1
    pcall(function()
        local RS = game:GetService("ReplicatedStorage")
        local petReg = require(RS.Data.PetRegistry)
        if petReg and petReg.PetConfig and petReg.PetConfig.WEIGHT_CONFIG then
            WEIGHT_SCALE_PER_LEVEL = petReg.PetConfig.WEIGHT_CONFIG.SCALE_PERCENTAGE_OF_BASE_WEIGHT_PER_LEVEL or 0.1
        end
    end)

    -- Calculate weight at age 1 from base weight
    local function getWeightAtAge1(baseWeight)
        if not baseWeight or baseWeight <= 0 then return 0 end
        return baseWeight * (1 + WEIGHT_SCALE_PER_LEVEL * 1)
    end

    -- Get weight range string (e.g., "6.01-6.09", "6.1-6.19")
    local function getWeightRange(weight)
        if not weight or weight <= 0 then return nil end

        local base = math.floor(weight * 10) / 10  -- e.g., 6.05 -> 6.0
        local rangeStart = base + 0.01
        local rangeEnd = base + 0.09

        return string.format("%.2f-%.2f", rangeStart, rangeEnd)
    end

    -- Scan inventory and build statistics for webhook
    function m:ScanInventoryStats()
        local stats = {
            teamComposition = {},   -- {petType = count}
            targetTypes = {},       -- {petType = true}
            boostingStats = {},     -- {petType = {total = N, ranges = {range = count}}}
            totalMaxKG = 0,
            remainsQueue = 0
        }

        local bag = getDatastoreBag()
        if not bag then return stats end

        -- Get target types from config
        stats.targetTypes = self.SelectedPetTypes or {}

        -- Build team composition
        if self.SelectedTeamPets and Pet then
            for guid, _ in pairs(self.SelectedTeamPets) do
                local petData = Pet:GetPetData(guid)
                if petData then
                    local petType = Pet:GetPetType(petData)
                    stats.teamComposition[petType] = (stats.teamComposition[petType] or 0) + 1
                end
            end
        end

        -- Scan all pets in inventory
        for guid, rec in pairs(bag) do
            if type(rec) == "table" then
                local PD = rec.PetData or rec.Data or {}
                local petType = rec.PetType or rec.Type or PD.Type or PD.PetType or "Unknown"
                local baseWeight = PD.BaseWeight or rec.BaseWeight or 0
                local isFavorite = PD.IsFavorite or rec.IsFavorite or PD.Favorited or rec.Favorited or false

                -- Only count target pet types (not favorited)
                if stats.targetTypes[petType] and not isFavorite then
                    if baseWeight >= self.TargetWeight then
                        -- Pet has reached max KG
                        stats.totalMaxKG = stats.totalMaxKG + 1

                        -- Initialize pet type stats if needed
                        if not stats.boostingStats[petType] then
                            stats.boostingStats[petType] = {
                                total = 0,
                                ranges = {}
                            }
                        end

                        stats.boostingStats[petType].total = stats.boostingStats[petType].total + 1

                        -- Add to weight range (using weight at age 1)
                        local weightAt1 = getWeightAtAge1(baseWeight)
                        local range = getWeightRange(weightAt1)
                        if range then
                            stats.boostingStats[petType].ranges[range] =
                                (stats.boostingStats[petType].ranges[range] or 0) + 1
                        end
                    else
                        -- Pet still in queue
                        stats.remainsQueue = stats.remainsQueue + 1
                    end
                end
            end
        end

        return stats
    end

    -- Send Elephant BOOST webhook
    function m:SendElephantWebhook()
        local G = getgenv and getgenv() or _G
        if not G.SpecialWebhook then return end

        local stats = self:ScanInventoryStats()

        pcall(function()
            G.SpecialWebhook:ElephantBoostStats(stats)
        end)
    end

    -- Save config to file
    function m:SaveConfig()
        pcall(function()
            -- Ensure base folder exists
            if not isfolder(SAVE_BASE) then
                makefolder(SAVE_BASE)
            end
            -- Ensure user folder exists
            if not isfolder(SAVE_DIR) then
                makefolder(SAVE_DIR)
            end

            local payload = {
                selectedTeamPets = self.SelectedTeamPets,
                targetWeight = self.TargetWeight,
                minAgeToEquip = self.MinAgeToEquip,
                unequipAtAge = self.UnequipAtAge,
                maxPetsInGarden = self.MaxPetsInGarden,
                selectedPetTypes = self.SelectedPetTypes,
                wasRunning = self.IsRunning, -- Save toggle state
                _ts = os.time()
            }

            local json = HttpService:JSONEncode(payload)
            writefile(SAVE_FILE, json)
            -- print("[Elephant] Config saved")
        end)
    end

    -- Load config from file
    function m:LoadConfig()
        if not isfile(SAVE_FILE) then
            -- print("[Elephant] No saved config, using defaults")
            return false
        end

        local success, err = pcall(function()
            local text = readfile(SAVE_FILE)
            local data = HttpService:JSONDecode(text)

            -- New format: direct pet GUIDs set
            if type(data.selectedTeamPets) == "table" then
                self.SelectedTeamPets = {}
                for guid, v in pairs(data.selectedTeamPets) do
                    if v then self.SelectedTeamPets[guid] = true end
                end
            elseif data.selectedTeam and data.selectedTeam ~= "" and PetTeam and PetTeam.GetTeam then
                -- Backward-compat: migrate from named team
                local team = PetTeam:GetTeam(data.selectedTeam)
                if team and team.pets then
                    self.SelectedTeamPets = {}
                    for _, guid in ipairs(team.pets) do
                        self.SelectedTeamPets[guid] = true
                    end
                end
            end
            if type(data.targetWeight) == "number" then
                self.TargetWeight = data.targetWeight
            end
            if type(data.minAgeToEquip) == "number" then
                self.MinAgeToEquip = data.minAgeToEquip
            end
            if type(data.unequipAtAge) == "number" then
                self.UnequipAtAge = data.unequipAtAge
            end
            if type(data.maxPetsInGarden) == "number" then
                self.MaxPetsInGarden = data.maxPetsInGarden
            end
            if type(data.selectedPetTypes) == "table" then
                self.SelectedPetTypes = {}
                for petType, isSelected in pairs(data.selectedPetTypes) do
                    if isSelected then
                        self.SelectedPetTypes[petType] = true
                    end
                end
            end

            -- Load saved running state for auto-resume
            self.WasRunning = data.wasRunning == true
        end)

        if not success then
            -- warn("[Elephant] Failed to load config:", err)
            return false
        end

        return true
    end

    function m:Init(_core, _pet, _petTeam)
        Core = _core
        Pet = _pet
        PetTeam = _petTeam

        -- Set username-based save path
        local username = Players.LocalPlayer and Players.LocalPlayer.Name or "Unknown"
        SAVE_DIR = SAVE_BASE .. "/" .. username
        SAVE_FILE = SAVE_DIR .. "/elephant_config.json"

        -- Load saved config
        self:LoadConfig()
        -- Auto-resume is now handled in UI init (elephant/ui_pandoruy.lua)
    end

    -- Send notification via callback
    function m:Notify(title, content, color)
        if self.OnNotify then
            self.OnNotify(title, content, color)
        end
    end

    -- Get skill cooldown for stuck detection (same as auto_kg)
    function m:GetSkillCooldown(uuid, tokens)
        if not uuid or uuid == "" then return nil end
        tokens = tokens or ALL_SKILL_TOKENS

        local cooldowns = nil
        pcall(function()
            local GameEvents = Core.ReplicatedStorage:WaitForChild("GameEvents", 2)
            local GetPetCooldownRF = GameEvents:WaitForChild("GetPetCooldown", 2)
            if GetPetCooldownRF then
                cooldowns = GetPetCooldownRF:InvokeServer(uuid)
            end
        end)

        if type(cooldowns) ~= "table" then return nil end

        for _, cd in ipairs(cooldowns) do
            local skill = string.lower(tostring(cd.Skill or cd.Passive or ""))
            for _, token in ipairs(tokens) do
                if skill:find(token, 1, true) then
                    local time = cd.Time
                    if type(time) == "number" then return time end
                    if type(time) == "string" then
                        local m, s = time:match("^(%d+)%s*:%s*(%d+)$")
                        if m and s then return tonumber(m) * 60 + tonumber(s) end
                        return tonumber(time:match("%-?%d+%.?%d*")) or 0
                    end
                end
            end
        end
        return nil
    end

    -- Check and fix stuck pets (same as auto_kg)
    function m:CheckStuckPets()
        if not self.SkillStuckEnabled then return end

        local activePets = Pet:GetActivePets() or {}
        local stuckPets = {}

        for _, guid in ipairs(activePets) do
            local cooldown = self:GetSkillCooldown(guid, ALL_SKILL_TOKENS)
            local rec = SKILL_STUCK[guid] or { lastCooldown = nil, sameCount = 0 }

            if cooldown == nil then
                rec.lastCooldown, rec.sameCount = nil, 0
            else
                if rec.lastCooldown ~= nil then
                    local diff = cooldown - r
